config/routes.rb
KepplerContactUs::Engine.routes.draw do
  namespace :admin do
    scope :contact_us, as: :contact_us do
      resources :messages do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: :clone
        post '/upload', action: :upload
        get '/download', action: :download
        get '/favorite', action: :favorite
        get '/reply', action: :reply
        get '/share', action: :share
        patch '/send', action: :send_message
        # post '/create', action: :create
        post '/sort', action: :sort, on: :collection
        get '/reload', action: :reload, on: :collection
        get '/sent', action: :sent, on: :collection
        get '/read', action: :read, on: :collection
        get '/unread', action: :unread, on: :collection
        get '/favorites', action: :favorites, on: :collection
        get '/settings', action: :settings, on: :collection
        delete '(page/:page)/destroy_multiple', action: :destroy_multiple, on: :collection
      end

    end
  end
end

app/models/keppler_contact_us/application_record.rb
module KepplerContactUs
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/keppler_contact_us/concerns/activity_history.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    # ActivityHistory Module
    module ActivityHistory
      extend ActiveSupport::Concern

      included do
        include PublicActivity::Model
        tracked owner: ->(controller, _) { controller && controller.current_user }
      end
    end
  end 
end

app/models/keppler_contact_us/concerns/clone_record.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    # Keppler
    module CloneRecord
      extend ActiveSupport::Concern

      # Class Methods
      module ClassMethods
        def clone_record(id)
          object = name.constantize.find(id)
          object.dup
        end
      end
    end
  end 
end

app/models/keppler_contact_us/concerns/downloadable.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    # Keppler
    module Downloadable
      extend ActiveSupport::Concern

      require 'csv'

      def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each { |object| csv << object.attributes.values }
        end
      end
    end
  end 
end

app/models/keppler_contact_us/concerns/messageable.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    module Messageable
      extend ActiveSupport::Concern
      included do
        def self.sent
          all.where(from_email: current_user.email)
        end 

        def self.select_all(attr)
          all.select(&:attr)
        end

        def self.reject_all(attr)
          all.reject(&:read)
        end

        def self.unread_count
          all.reject(&:read).count
        end
      end
    end
  end
end

app/models/keppler_contact_us/concerns/sortable.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    # Keppler
    module Sortable
      extend ActiveSupport::Concern
      included do
        def self.sorter(params)
          params.each_with_index do |id, idx|
            find(id).update(position: idx.to_i + 1)
          end
        end
      end
    end
  end 
end

app/models/keppler_contact_us/concerns/uploadable.rb
# frozen_string_literal: true

# KepplerContactUs
module KepplerContactUs
  module Concerns
    # Keppler
    module Uploadable
      extend ActiveSupport::Concern

      require 'csv'

      def self.upload(file)
        CSV.foreach(file.path, headers: true) { |row| create! row.to_hash }
      end
    end
  end 
end

app/models/keppler_contact_us/message_setting.rb
#Generado por keppler
module KepplerContactUs
  class MessageSetting < ActiveRecord::Base
    include CloneRecord

    # Fields for the search form in the navbar
    def self.search_field
      :mailer_to_or_mailer_from
    end
  end
  #MessageSetting.import
end

app/controllers/keppler_contact_us/admin/messages_controller.rb
require_dependency 'keppler_contact_us/application_controller'
module KepplerContactUs
  module Admin
    # MessagesController
    class MessagesController < ApplicationController
      layout 'keppler_contact_us/admin/layouts/application'
      before_action :authenticate_user!
      skip_before_action :verify_authenticity_token
      include KepplerContactUs::Concerns::ObjectQuery
      include KepplerContactUs::Concerns::Commons
      include KepplerContactUs::Concerns::History
      include KepplerContactUs::Concerns::DestroyMultiple

      before_action :folders
      before_action :labels

      # GET /messages
      def index 
        respond_to_formats(model.all)
        redirect_to_index if nothing_in_first_page?(@objects)
      end
      
      def new
        @object = model.new
      end
      
      def create
        message_params[:to_emails].split(', ')
        @object = model.new(message_params)
        if @object.save
          KepplerContactUs::Admin::MessageMailer.with(object: @object).send_mail(@object).deliver_now
          flash[:notice] = actions_messages(@objects)
        end
        redirect_to_index
      end

      # GET /messages/1
      def show
        @object.update(read: true)
      end

      # DELETE /messages/1
      def destroy
        @object.destroy
        redirect_to_index
      end

      def destroy_multiple
        model.destroy redefine_ids(params[:multiple_ids])
        redirect_to_index
      end

      def favorite
        @object.update(favorite: (@object.favorite ? false : true))
      end

      def sort
        model.sorter(params[:row])
        redirect_to_index
      end
      
      def send_message
        message_params[:to_emails].split(', ')
        @object = model.new(message_params)
        if @object.save
          KepplerContactUs::Admin::MessageMailer.with(object: @object).send_mail(@object).deliver_now
          flash[:notice] = actions_messages(@objects)
        end
        redirect_to_index
      end

      def sent
        objects_where(from_email: current_user.email)
      end
      
      def read
        objects_where(read: true)
      end
      
      def unread
        objects_where(read: !true)
      end

      def favorites
        objects_where(favorite: true)
      end

      def settings
        @setting = ::Setting.first
        @render = 'email_setting'
        # @social_medias = social_account_permit_attributes
        # @colors = social_account_colors
      end

      # def reply
      # end 
      
      # def share
      # end

      private

      def objects_where(condition)
        query = @q.result(distinct: true)
        filtered_objects = query.where(condition).order(position: :desc)
        if action_name.eql?('read')
          no_current_user_messages = model.reject_current_user_email
          no_current_user_ids = no_current_user_messages.map(&:id)
          filtered_objects = filtered_objects.where(id: no_current_user_ids)
        end
        @objects = filtered_objects.page(@current_page)
        @total = filtered_objects.size
        respond_to_formats(@objects)
      end

      def folders
        @folders = YAML.load_file(
          "rockets/keppler_contact_us/config/folders.yml"
        ).values.each(&:symbolize_keys!)
      end
      
      def labels
        @labels = YAML.load_file(
          "rockets/keppler_contact_us/config/labels.yml"
        ).values.each(&:symbolize_keys!)
      end

      # Only allow a trusted parameter 'white list' through.
      def message_params
        params.require(:message).permit(
          :name,
          :from_email,
          # { to_emails: [] },
          :to_emails,
          :subject,
          :content,
          :favorite,
          :read,
          :position,
          :deleted_at
        )
      end
    end
  end
end

app/controllers/keppler_contact_us/application_controller.rb
module KepplerContactUs
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/keppler_contact_us/concerns/commons.rb
module KepplerContactUs
  module Concerns
    # Concern con la configuracion de parametros de los formulario
    module Commons
      extend ActiveSupport::Concern

      included do
        before_action :paginator_params
        before_action :set_setting
        before_action :this_object, only: %i[show edit update destroy favorite reply share]
        before_action :query_objects#, only: %i[index reload sort favorite]
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def this_object
        param_id = params[:id] || params["#{controller_name.singularize}_id".to_sym]
        return if param_id.nil? || param_id.to_i.zero?
        @object = model.find(param_id)
      end

      def query_objects
        @q = model.ransack(params[:q])
        q = @q.result(distinct: true)
        @objects = q.page(@current_page).order(position: :desc)
        @total = q.size
      end

      def paginator_params
        @search_field = model.search_field if listing?
        @query = params[:search] unless params[:search].blank?
        @current_page = params[:page] unless params[:page].blank?
      end
      
      def module_name
        controller_path.split('/').split('admin').flatten.join('/').classify.constantize
      end

      # Get submit key to redirect, only [:create, :update]
      def redirect(object, commit)
        if commit.key?('_save')
          redirect_to([:admin, :ckn, object], notice: actions_messages(object))
        elsif commit.key?('_add_other')
          redirect_to(
            send("new_admin_#{underscore(object)}_path"),
            notice: actions_messages(object)
          )
        end
      end
    end
  end
end

app/controllers/keppler_contact_us/concerns/destroy_multiple.rb
module KepplerContactUs
  module Concerns
    # Concern con la configuracion de parametros de los formulario
    module DestroyMultiple
      extend ActiveSupport::Concern

      included do
        before_action :can_multiple_destroy, only: [:destroy_multiple]
      end

      private

<<<<<<< HEAD
=======
      def model
        ctrlpath = controller_path
        klass = ctrlpath.split('/').split('admin').flatten.join('/')
        klass.classify.constantize
      end

>>>>>>> e85f7aa49cacc350fa3b8e864ce1a3461b2667b9
      def redefine_ids(ids)
        ids.delete('[]').split(',').select do |id|
          id if model.exists? id
        end
      end

      # Check whether the user has permission to delete
      # each of the selected objects
      def can_multiple_destroy
        redefine_ids(params[:multiple_ids]).each do |id|
          authorize model
        end
      end
    end
  end
end

app/controllers/keppler_contact_us/concerns/history.rb
module KepplerContactUs
  module Concerns
    # Concern con la configuracion de parametros de los formulario
    module History
      extend ActiveSupport::Concern

      included do
        before_action :show_history, only: %i[index]
      end

      private

      def show_history
        get_history(model)
      end

      def get_history(model)
        @activities = PublicActivity::Activity.where(
          trackable_type: model.to_s
        ).order('created_at desc').limit(50)
      end
    end
  end
end

app/controllers/keppler_contact_us/concerns/object_query.rb
# frozen_string_literal: true

module KepplerContactUs
  module Concerns
    # ObjectQuery
    module ObjectQuery
      extend ActiveSupport::Concern

      private

      def redirect_to_index
        redirect_to(
          {
            action: :index,
            page: (@current_page.to_i if params[:page]),
            search: @query
          },
          notice: actions_messages(model.new)
        )
      end

      def nothing_in_first_page?(objects)
        !objects.first_page? && objects.size.zero?
      end

      def send_format_data(objects, extension)
        models = objects.model.to_s.downcase.pluralize
        t_models = t("keppler.models.pluralize.#{models}").humanize
        filename = "#{t_models} - #{I18n.l(Time.now, format: :short)}"
        obj_ar = objects.order(:created_at).to_a
        case extension
        when 'csv' then send_data obj_ar.to_csv, filename: "#{filename}.csv"
        when 'xls' then send_data obj_ar.to_xls, filename: "#{filename}.xls"
        end
      end

      def respond_to_formats(objects)
        respond_to do |format|
          format.html
          format.csv { send_data objects.model.all.to_csv }
          format.xls { send_data objects.model.all.to_xls }
          format.json { render json: json_objects(objects) }
        end
      end

      protected

      def json_objects(objects)
        if action_name.eql?('index')
          if request.url.include?('page')
            objects.page(@current_page).order(position: :desc)
          else
            objects.model.all
          end
        else 
          objects
        end
      end
    end
  end
end

app/controllers/keppler_contact_us/message_settings_controller.rb
#Generado con Keppler.
require_dependency "keppler_contact_us/application_controller"

module KepplerContactUs
  class MessageSettingsController < ApplicationController
    before_filter :authenticate_user!
    layout 'admin/layouts/application'
    load_and_authorize_resource
    before_action :set_message_setting, only: [:edit, :update]

    # GET /message_settings/1/edit
    def edit
    end

    # PATCH/PUT /message_settings/1
    def update
      if @message_setting.update(message_setting_params)
        redirect_to edit_message_settings_path(@message_setting), notice: 'Message setting was successfully updated.'
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_message_setting
        @message_setting = MessageSetting.first
        unless @message_setting
          @message_setting = KepplerContactUs::MessageSetting.create(mailer_from: 'info@keppler.com', mailer_to: 'info@keppler.com')
        end
      end

      # Only allow a trusted parameter "white list" through.
      def message_setting_params
        params.require(:message_setting).permit(:mailer_to, :mailer_from)
      end
  end
end

app/controllers/keppler_contact_us/messages_controller.rb
#Generado con Keppler.
require_dependency "keppler_contact_us/application_controller"

module KepplerContactUs
  class MessagesController < Admin::AdminController
    before_filter :authenticate_user!, except: [:create]
    layout 'admin/layouts/application', except: [:new]
    load_and_authorize_resource except: [:create]
    before_action :set_message, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /messages
    def index
      @q = Message.ransack(params[:q])
      messages = @q.result(distinct: true).order("created_at DESC")
      @objects = messages.page(@current_page)
      @total = messages.size

      if !@objects.first_page? && @objects.size.zero?
        redirect_to(
          posts_path(page: @current_page.to_i.pred, search: @query)
        )
      end

    end

    # GET /messages/1
    def show
      @objects = Message.all
      @reply = Message.new
      message = Message.find_by(id: params[:id])
      # @reply = Message.new(reply_id: message.id)
      message.update(read: true) unless message.read
    end

    # POST /messages
    def create
      @message = Message.new(message_params)
      if !verify_recaptcha(model: @message, timeout: 10, message: "Oh! It's error with reCAPTCHA!") and @message.save
        ContactMailer.contact(@message).deliver_now
        redirect_to KepplerContactUs.redirection, notice: t('keppler.messages.sent_message')
      else
        redirect_to KepplerContactUs.redirection, alert: t('keppler.messages.error_message')
      end
    end

    # DELETE /messages/1
    def destroy
      @message.destroy
      redirect_to messages_url, notice: actions_messages(@message)
    end

    def destroy_multiple
      Message.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        messages_path(page: @current_page, search: @query),
        notice: actions_messages(Message.new)
      )
    end

    def reply
      @message = Message.new(message_params)
      ReplyMailer.contact(@message, params[:to]).deliver_now
      redirect_to KepplerContactUs.redirection, notice: t('keppler.messages.sent_message')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:name, :subject, :email, :content, :read)
    end

    def show_history
      get_history(Message)
    end
  end
end

app/helpers/keppler_contact_us/application_helper.rb
module KepplerContactUs
  module ApplicationHelper
    def model
      controller_path.split('/').split('admin').flatten.join('/').classify.constantize
    end

    def module_name
      controller_path.split('/').split('admin').flatten.join('/').classify.constantize
    end
  end
end

app/helpers/keppler_contact_us/messages_helper.rb
module KepplerContactUs
  module MessagesHelper
  end
end

app/views/keppler_contact_us/messages/_folders.html.haml
-# %a.btn.btn-primary.btn-block.margin-bottom{:href => "compose.html"}= t("keppler.messages.compose")
.box.box-solid
	.box-header.with-border
		%h3.box-title= t("keppler.messages.folder")
		.box-tools
			%button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
				%i.fa.fa-minus
	.box-body.no-padding
		%ul.nav.nav-pills.nav-stacked
			%li
				%a{:href => "/admin/messages"}
					%i.fa.fa-inbox
					= t("keppler.messages.inbox")
					- if !@objects.count.zero?
						%span.label.label-primary.pull-right
							= @objects.count
			%li
				%a{:href => "#"}
					%i.fa.fa-envelope-o
					= t("keppler.messages.sent")

app/views/keppler_contact_us/messages/_form.html.haml
.contact-form
	= render "app/layouts/messages"
	= simple_form_for @message, :url => "/admin/messages", :method => :post do |f|
		.row
			.col-lg-12
				= f.input :name, label: false,  input_html: {class: "form-control", placeholder: "Nombre", required: "required"}

			.col-lg-12
				= f.input :email, as: :email, label: false, input_html: {class: "form-control", placeholder: "Email", required: "required"}

			.col-lg-12
				= f.input :subject, label: false, input_html: {class: "form-control", placeholder: "Asunto"}

			.col-lg-12
				= f.input :content, as: :text, label: false, input_html: {class: "form-control", placeholder: "Mensaje..."}
		.row
			.col-lg-12
				= raw recaptcha_tags :display => { :theme => 'custom', lang: 'es' }, ajax: true

			.col-lg-12.form-actions.right
				= f.button :submit, t('keppler.actions.send'), class: "btn btn-primary pull-right"

app/views/keppler_contact_us/messages/_index_show.html.haml
.listing-show-header
	.actions
	%h5
		= material_icon.md_24.email.css_class("md-light")
		= t("keppler.models.singularize.#{controller_path.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		.card-content
			%li.list-row
				.display-label= model.human_attribute_name(:name)
				.display-value= @message.name
			%li.list-row
				.display-label= model.human_attribute_name(:subject)
				.display-value= @message.subject
			%li.list-row
				.display-label= model.human_attribute_name(:email)
				.display-value= @message.email
			%hr
			.display-value{align: "justify"}= @message.content
			%br/
			%br/
			%li.list-row
				= link_to t('keppler.actions.back_history'), messages_path


:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/keppler_contact_us/messages/_listing.html.haml
%tr{ id: "row-#{message.id}" }
	- if can? :destroy_multiple, KepplerContactUs::Message
		%td.item-check{style:"width: 5%"}
			= link_to "", message_path(message), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{message.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{message.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{message.id}" }

		%td{style:"width: 5%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				- if message.read
					%i.icon-envelope-open
				- else
					%i.icon-envelope
		%td{style:"width: 15%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				= link_to message_path(message, search: @query) do
					= message.name
		%td.hide-on-small-and-down{style:"width: 55%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				= "<b>#{message.subject}</b> - #{message.content.truncate(40)}".html_safe
		%td.hide-on-small-and-down{style:"width: 40%"}
			= link_to "", message_path(message, search: @query), remote: true, class: "show-row"
			%span
				.pull-right
					= time_ago_in_words(message.created_at)

app/views/keppler_contact_us/messages/index.html.haml
= title(t('keppler.titles.index', model: t("keppler.models.pluralize.messages")))

.container
  .row
    .col-md-3
      = render 'keppler_contact_us/messages/folders'

    .col-lg-9
      .box.slice-box
        .box-header.with-border
          %h3.box-title= t("keppler.messages.inbox")
          / /.box-tools
        / /.box-header
        .box-body.no-padding
          .mailbox-controls
            / Check all button
            %button.btn.btn-default.btn-sm.checkbox-toggle{:type => "button"}
              %i.fa.fa-square-o
            .btn-group
              %button.btn.btn-default.btn-sm{:type => "button"}
                %i.fa.fa-trash-o
            / /.btn-group
            %button.btn.btn-default.btn-sm{:type => "button"}
              %i.fa.fa-refresh
            .pull-right
              = entries(@total, @objects)
              .btn-group
                %button.btn.btn-default.btn-sm{:type => "button"}
                  %i.fa.fa-chevron-left
                %button.btn.btn-default.btn-sm{:type => "button"}
                  %i.fa.fa-chevron-right
              / /.btn-group
            / /.pull-right
        .table-responsive.mailbox-messages
          %table.table.table-hover.table-striped
            %tbody
            - @objects.each do |message|
              = render 'listing', message: message
              - if @objects.size.zero?
                %tr
                %td{colspan: "4"}
                  %center
                    = t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.messages"))

          = paginate @objects, window: 1

app/views/keppler_contact_us/messages/new.html.haml
= title "Messages - Nuevo"
= render 'form'

app/views/keppler_contact_us/messages/show.html.haml
= title(t('keppler.titles.show', model: t("keppler.models.pluralize.messages")))
.col-md-3
	= render 'keppler_contact_us/messages/folders'

.col-lg-9
	.box.slice-box
		.box-header.with-border
			.pull-right
				= link_to message_path(@message), class: "btn btn-default", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					%i.icon-trash
					Delete

		.box-body.no-padding
			.mailbox-read-info
				%h3= @message.subject
				%h5
					= "#{t('keppler.messages.from')}: #{@message.email}"
					%span.mailbox-read-time.pull-right= time_ago_in_words(@message.created_at)
			.mailbox-read-message
				= @message.content
		.box-footer

			.box.slice-box
				.box-header.with-border
					%h3.box-title
						Responder a
						%strong= "#{@message.email}"

				= simple_form_for @reply, url: message_reply_path(@message), :method => :post do |f|
					.box-body
						.form-group
							%input{type: "hidden", name: "Hacia", value: "#{@message.email}"}
							%input.form-control{:placeholder => "To: #{@message.email}", disabled: "disabled", name: "to"}/
						.form-group
							= f.input :subject, label: false, placeholder: "asunto"
						.form-group
							= f.input :content, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }
					.box-footer
						.pull-right
							= f.submit "Enviar", class: "btn-primary"

app/views/keppler_contact_us/messages/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@message.id}").addClass("active")
- if KepplerContactUs::Message.where({read: nil}).count > 0
	$("#badge-message").html("#{KepplerContactUs::Message.where({read: nil}).count}")
- else
	$("#badge-message").html("")
$('#read-status-#{@message.id}').html("<i class='mi md-18  md-dark'>done</i>");
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");